[package]
name = "UStream"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28" 
egui = "0.24"   
image = "0.24"
scrap = "0.5.0" 
bytes = "1.4" 
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3" 